### ISSUE TITLE
Добавить скорость 460800 и 921600

### ISSUE THREAD

**Issue by karasevia** [badlogic/serial-plotter#1]
Вышло невероятно круто. Я в полном восторге от вашей работы.
Я обычно использую большую скорость чем максимальная у вас и прошу их сделать доступными для всех. (Понимаю что можно сделать fork), но думаю добавить два варианта вам будет проще.

Дополнительная часть.
```
>voltage:3284,current:6383
>voltage:3284,current:5882
>voltage:3260,current:5928
>voltage:3252,current:6047
Simple log string
>voltage:3252,current:5960
>voltage:3272,current:5886
>voltage:3264,current:6292
>voltage:3252,current:6420
>voltage:3264,current:6325
```

В вашей версии используется символ ">" в начале строки, чтобы обозначить что сейчас будут новые значения. Было бы здорово, если бы было еще одно окно с терминалом, в котором были бы строки, начинающиеся не с этого символа.

```
Simple log string
```

Спасибо еще раз, за ваш труд

**Comment by badlogic** [comment]
I'll add a checkbox that lets you hide/show the `>` lines in the `Raw` panel. Does this sound good?

**Comment by badlogic** [comment]
Oh, and regarding the baud rate, just let me know what your max is and I'll add more options.

**Comment by badlogic** [comment]
Oki, I made it so lines starting with > can be hidden in the `Raw` pane, and added additional baud rates.

**Comment by karasevia** [comment]
Все просто великолепно. В скоростях выше 921600 лично я не вижу необходимости. Все что есть работает идеально, скрывать лог хорошая идея, уже использую ее
